In [7]:
#Realice un programa que sume, reste, multiplique (producto punto y producto cruz) y divida dos
#vectores previamente inicializados.
import numpy as np

# Función para realizar la suma de dos vectores
def suma_vectores(v1, v2):
    return v1 + v2

# Función para realizar la resta de dos vectores
def resta_vectores(v1, v2):
    return v1 - v2

# Función para realizar el producto punto entre dos vectores
def producto_punto(v1, v2):
    return np.dot(v1, v2)

# Función para realizar el producto cruz entre dos vectores
def producto_cruz(v1, v2):
    return np.cross(v1, v2)

# Función para realizar la división de dos vectores
def division_vectores(v1, v2):
    # Suponiendo que quieres dividir elemento por elemento
    return v1 / v2

# Vectores de ejemplo
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Suma de vectores
print("Suma:", suma_vectores(vector1, vector2))

# Resta de vectores
print("Resta:", resta_vectores(vector1, vector2))

# Producto punto
print("Producto Punto:", producto_punto(vector1, vector2))

# Producto cruz
print("Producto Cruz:", producto_cruz(vector1, vector2))

# División de vectores
print("División:", division_vectores(vector1, vector2))

Suma: [5 7 9]
Resta: [-3 -3 -3]
Producto Punto: 32
Producto Cruz: [-3  6 -3]
División: [0.25 0.4  0.5 ]


In [2]:
#Realice un programa que sume, reste, multiplique (producto punto y producto cruz) y divida dos
#matrices previamente inicializadas.
import numpy as np

matrizA = np.array([[1,2],[3,4],[5,6]],float)
matrizB = np.array([[4,6],[4,3],[1,2]],float)
suma=matrizA + matrizB
resta=matrizA-matrizB
multiplicacion=matrizA*matrizB
divicion=matrizA*matrizB
print(f"suma de matrices: \n {suma} \n resta de matrices: \n {resta} \n multiplicacion de matrices: \n {multiplicacion} \n divicion de matrices:\n {divicion}")

suma de matrices: 
 [[5. 8.]
 [7. 7.]
 [6. 8.]] 
 resta de matrices: 
 [[-3. -4.]
 [-1.  1.]
 [ 4.  4.]] 
 multiplicacion de matrices: 
 [[ 4. 12.]
 [12. 12.]
 [ 5. 12.]] 
 divicion de matrices:
 [[ 4. 12.]
 [12. 12.]
 [ 5. 12.]]


In [5]:

#Realice un programa que convierta coordenadas rectangulares a cilíndricas y esféricas, para lo cual
#deben consultar sobre el uso de funciones trigonométricas en Python. 
import math

def rectangular_a_cilindricas(x, y, z):
    rho = math.sqrt(x**2 + y**2)  # Distancia radial desde el origen al punto en el plano xy
    phi = math.atan2(y, x)         # Ángulo en el plano xy (en radianes)
    z_cilindrica = z                # La coordenada z en el sistema cilíndrico es la misma que en el rectangular
    return rho, phi, z_cilindrica

def rectangular_a_esfericas(x, y, z):
    rho = math.sqrt(x**2 + y**2 + z**2)   # Distancia radial desde el origen al punto
    phi = math.atan2(y, x)                 # Ángulo en el plano xy (en radianes)
    theta = math.acos(z / rho)             # Ángulo con el eje z (en radianes)
    return rho, phi, theta

# Función principal
def main():
    # Pedir al usuario las coordenadas rectangulares
    x = float(input("Ingrese la coordenada x: "))
    y = float(input("Ingrese la coordenada y: "))
    z = float(input("Ingrese la coordenada z: "))

    # Convertir a coordenadas cilíndricas
    rho_cil, phi_cil, z_cil = rectangular_a_cilindricas(x, y, z)
    print("\nCoordenadas cilíndricas:")
    print("Rho:", rho_cil)
    print("Phi (ángulo en radianes):", phi_cil)
    print("Z:", z_cil)

    # Convertir a coordenadas esféricas
    rho_esf, phi_esf, theta_esf = rectangular_a_esfericas(x, y, z)
    print("\nCoordenadas esféricas:")
    print("Rho:", rho_esf)
    print("Phi (ángulo en radianes):", phi_esf)
    print("Theta (ángulo en radianes):", theta_esf)

if __name__ == "__main__":
    main()


Coordenadas cilíndricas:
Rho: 6.4031242374328485
Phi (ángulo en radianes): 0.6747409422235526
Z: 3.0

Coordenadas esféricas:
Rho: 7.0710678118654755
Phi (ángulo en radianes): 0.6747409422235526
Theta (ángulo en radianes): 1.1326472962107264


In [6]:
#Realice un programa para el cálculo de la resistencia de una RTD de platino (PT100) en función de
#la temperatura.
def calcular_resistencia(temp):
    # Coeficientes de la ecuación de Callendar-Van Dusen
    a = 3.9083e-3
    b = -5.775e-7
    # Temperatura de referencia
    t0 = 100.0
    # Resistencia a temperatura de referencia
    r0 = 100.0

    # Cálculo de la resistencia
    r = r0 * (1 + a * temp + b * temp**2)

    return r

# Temperatura en grados Celsius
temperatura = 25.0

# Calcular resistencia
resistencia = calcular_resistencia(temperatura)

# Imprimir resultado
print(f"La resistencia de la RTD a {temperatura} grados Celsius es {resistencia} ohmios.")

La resistencia de la RTD a 25.0 grados Celsius es 109.73465625 ohmios.


In [8]:
#5.Realice en funciones las rotaciones en X, Y y Z, donde se tenga un parámetro de entrada (ángulo)
#y un parámetro de salida (matriz).
import numpy as np

# Función para la rotación en el eje X
def rotacion_x(angulo):
    radianes = np.radians(angulo)
    matriz_rotacion_x = np.array([
        [1, 0, 0],
        [0, np.cos(radianes), -np.sin(radianes)],
        [0, np.sin(radianes), np.cos(radianes)]
    ])
    return matriz_rotacion_x

# Función para la rotación en el eje Y
def rotacion_y(angulo):
    radianes = np.radians(angulo)
    matriz_rotacion_y = np.array([
        [np.cos(radianes), 0, np.sin(radianes)],
        [0, 1, 0],
        [-np.sin(radianes), 0, np.cos(radianes)]
    ])
    return matriz_rotacion_y

# Función para la rotación en el eje Z
def rotacion_z(angulo):
    radianes = np.radians(angulo)
    matriz_rotacion_z = np.array([
        [np.cos(radianes), -np.sin(radianes), 0],
        [np.sin(radianes), np.cos(radianes), 0],
        [0, 0, 1]
    ])
    return matriz_rotacion_z

# Ejemplo de uso
angulo = 60  # Ángulo en grados


# Rotación en el eje X
print("Angulo de rotación", angulo)
matriz_rotacion_x = rotacion_x(angulo)
print("Matriz de rotación en el eje X:")
print(matriz_rotacion_x)

# Rotación en el eje Y
print("Angulo de rotación", angulo)
matriz_rotacion_y = rotacion_y(angulo)
print("\nMatriz de rotación en el eje Y:")
print(matriz_rotacion_y)

# Rotación en el eje Z
print("Angulo de rotación", angulo)
matriz_rotacion_z = rotacion_z(angulo)
print("\nMatriz de rotación en el eje Z:")
print(matriz_rotacion_z)

Angulo de rotación 60
Matriz de rotación en el eje X:
[[ 1.         0.         0.       ]
 [ 0.         0.5       -0.8660254]
 [ 0.         0.8660254  0.5      ]]
Angulo de rotación 60

Matriz de rotación en el eje Y:
[[ 0.5        0.         0.8660254]
 [ 0.         1.         0.       ]
 [-0.8660254  0.         0.5      ]]
Angulo de rotación 60

Matriz de rotación en el eje Z:
[[ 0.5       -0.8660254  0.       ]
 [ 0.8660254  0.5        0.       ]
 [ 0.         0.         1.       ]]


In [10]:
#Realice un programa que calcule la fuerza de avance y retroceso de un cilindro neumático de doble
#efecto. Debe establecer previamente los valores de presión, así como las dimensiones físicas del
#cilindro para realizar el cálculo.
import math

def calcular_fuerza_avance(presion, radio_piston):
    area_avance = math.pi * (radio_piston ** 2)
    return presion * area_avance

def calcular_fuerza_retroceso(presion, radio_piston, diametro_varilla):
    radio_varilla = diametro_varilla / 2
    area_retroceso = math.pi * (radio_piston * 2) - math.pi * (radio_varilla * 2)
    return presion * area_retroceso

# Entradas del usuario
presion = float(input("Ingrese la presión del aire (en Pa): "))
radio_piston = float(input("Ingrese el radio del pistón (en metros): "))
diametro_varilla = float(input("Ingrese el diámetro de la varilla (en metros): "))

# Cálculo de fuerzas
fuerza_avance = calcular_fuerza_avance(presion, radio_piston)
fuerza_retroceso = calcular_fuerza_retroceso(presion, radio_piston, diametro_varilla)

# Mostrar resultados
print(f"Fuerza de avance: {fuerza_avance} N")
print(f"Fuerza de retroceso: {fuerza_retroceso} N")


Fuerza de avance: 15707.963267948966 N
Fuerza de retroceso: 0.0 N


In [12]:
#7.Realice un programa que calcule la potencia que consume un circuito ingresando por teclado el
#valor de corriente y voltaje.
# Solicitar al usuario que ingrese el voltaje y la corriente
voltaje = float(input("Ingrese el valor del voltaje (en voltios): "))
corriente = float(input("Ingrese el valor de la corriente (en amperios): "))

# Calcular la potencia y mostrar el resultado
print("La potencia consumida por el circuito es:", voltaje * corriente, "vatios.")

La potencia consumida por el circuito es: 480.0 vatios.


In [13]:
# 8.Realice un programa que calcule X números aleatorios en un rango determinado por el usuario.
import random

def generar_numeros_aleatorios(cantidad, rango_min, rango_max):
    numeros_aleatorios = []
    for _ in range(cantidad):
        numero_aleatorio = random.uniform(rango_min, rango_max)
        numeros_aleatorios.append(numero_aleatorio)
    return numeros_aleatorios

# Entradas del usuario
cantidad_numeros = int(input("Ingrese la cantidad de números aleatorios a generar: "))
rango_min = float(input("Ingrese el límite inferior del rango: "))
rango_max = float(input("Ingrese el límite superior del rango: "))

# Generar números aleatorios
numeros_generados = generar_numeros_aleatorios(cantidad_numeros, rango_min, rango_max)

# Mostrar resultados
print(f"{cantidad_numeros} números aleatorios en el rango [{rango_min}, {rango_max}]:")
print(numeros_generados)

20 números aleatorios en el rango [10.0, 10.0]:
[10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]


In [14]:
#9.Realice un programa para el cálculo de volúmenes (Prisma, Pirámide, Cono truncado, Cilindro)
#donde el usuario pueda seleccionar el sólido y los parámetros de cada volumen. 
import math

# Funciones para calcular el volumen de cada sólido
def volumen_prisma(base, altura):
    return base * altura

def volumen_piramide(base, altura):
    return (1/3) * base * altura

def volumen_cono_truncado(radio1, radio2, altura):
    return (1/3) * math.pi * altura * (radio1**2 + radio1*radio2 + radio2**2)

def volumen_cilindro(radio, altura):
    return math.pi * radio**2 * altura

# Diccionario que mapea las opciones del usuario a las funciones de cálculo de volumen
opciones = {
    1: volumen_prisma,
    2: volumen_piramide,
    3: volumen_cono_truncado,
    4: volumen_cilindro
}

# Función principal
def main():
    opcion = int(input("Seleccione el sólido para calcular su volumen:\n1. Prisma\n2. Pirámide\n3. Cono Truncado\n4. Cilindro\n"))

    if opcion not in opciones:
        print("Opción no válida.")
        return

    parametros = []

    # Solicitar los parámetros necesarios para el cálculo del volumen
    for parametro in opciones[opcion].__code__.co_varnames:
        if parametro != 'altura':
            valor = float(input(f"Ingrese la medida de {parametro}: "))
            parametros.append(valor)
        else:
            altura = float(input("Ingrese la altura: "))
            parametros.append(altura)

    # Calcular el volumen y mostrar el resultado
    volumen = opciones[opcion](*parametros)
    print("El volumen del sólido seleccionado es:", volumen)

if __name__ == "__main__":
    main()


   
        

El volumen del sólido seleccionado es: 200.0


In [15]:
#10.Realice un programa que le permita al usuario escoger entre robot Cilíndrico, Cartesiano y esférico,
#donde como respuesta a la selección conteste con el tipo y número de articulaciones que posee.
def main():
    print("Seleccione el tipo de robot:")
    print("1. Robot Cilíndrico")
    print("2. Robot Cartesiano")
    print("3. Robot Esférico")

    opcion = int(input("Ingrese el número de opción: "))

    if opcion == 1:
        print("\nRobot Cilíndrico")
        print("Número de articulaciones: 3")
    elif opcion == 2:
        print("\nRobot Cartesiano")
        print("Número de articulaciones: 3")
    elif opcion == 3:
        print("\nRobot Esférico")
        print("Número de articulaciones: 3")
    else:
        print("Opción inválida. Por favor, seleccione una opción válida.")

if __name__ == "__main__":
    main()

Seleccione el tipo de robot:
1. Robot Cilíndrico
2. Robot Cartesiano
3. Robot Esférico

Robot Cilíndrico
Número de articulaciones: 3


In [16]:
#11.Escribir un programa que realice la pregunta ¿Desea continuar Si/No? y que no deje de hacerla
#hasta que el usuario teclee No.
def continuar():
    while True:
        respuesta = input("¿Desea continuar? (Si/No): ").strip().lower()
        if respuesta == 'no':
            print("ok")
            break
        elif respuesta != 'si':
            print("si o no")

continuar()

¡Hasta luego!


In [ ]:
#12.Realice un programa que grafique el comportamiento de un sensor PT100 desde -200°C a 200°C

import numpy as np
import matplotlib.pyplot as plt

# Función para calcular la resistencia de la PT100
def resistencia_pt100(temperatura):
    # Coeficientes de la ecuación de Callendar-Van Dusen
    a = 3.9083e-3
    b = -5.775e-7
    R0 = 100.0  # Resistencia a 0°C

    return R0 * (1 + a * temperatura + b * temperatura**2)

# Rango de temperaturas de -200°C a 200°C
temperaturas = np.linspace(-200, 200, 1000)

# Calcular las resistencias correspondientes
resistencias = resistencia_pt100(temperaturas)

# Graficar
plt.figure(figsize=(10, 6))
plt.plot(temperaturas, resistencias, color='blue')
plt.title('Comportamiento de un sensor PT100')
plt.xlabel('Temperatura (°C)')
plt.ylabel('Resistencia (Ohm)')
plt.grid(True)
plt.show()

In [17]:
#.13 Realice un programa que le permita al usuario ingresar los coeficientes de una función de
#transferencia de segundo orden y graficar su comportamiento, además se debe mostrar que tipo
#de sistema es: subamortiguado, criticamente amortiguado y sobreamortiguado.
import numpy as np
import matplotlib.pyplot as plt

# Coeficientes de la función de transferencia
K = float(input("Ingrese la ganancia del sistema (K): "))
zeta = float(input("Ingrese el factor de amortiguamiento (zeta): "))
omega_n = float(input("Ingrese la frecuencia natural no amortiguada (omega_n): "))

# Graficar la respuesta en frecuencia
s = np.linspace(0, 10, 1000)
H = K / (s**2 + 2 * zeta * omega_n * s + omega_n**2)
plt.plot(s, np.abs(H))
plt.title('Respuesta en Frecuencia')
plt.xlabel('Frecuencia Angular (s)')
plt.ylabel('|H(s)|')
plt.grid(True)
plt.show()

# Determinar y mostrar el tipo de sistema
if zeta < 1:
    print("El sistema es subamortiguado.")
elif zeta == 1:
    print("El sistema es críticamente amortiguado.")
else:
    print("El sistema es sobreamortiguado.")

ModuleNotFoundError: No module named 'matplotlib'